services:
  lambda:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
       PYTHON_VERSION: $PYTHON_VERSION
       INSTALL_WATCHFILES: true
    image: forecast_lambda_renault:${TAG:-latest}
    env_file:
      - .env
    volumes:
      - ./src:/var/task
    ports:
      - "9000:8080"
    entrypoint: [""]
    command: ["watchfiles", "/usr/local/bin/aws-lambda-rie python -m awslambdaric lambda_function.handler", "/var/task"]