services:
  lambda:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        PYTHON_VERSION: $PYTHON_VERSION
    image: python_production_lambda:${TAG:-latest}
    env_file:
      - .env
    ports:
      - "9000:8080"
